POST http://localhost:3333/peoples
Content-Type: application/json

{
    "name": "Dykson Victor",
    "email": "dykson.marques@gmail.com",
    "birthDate": "1996-06-06",
    "cpf": "47930854825",
    "phone": "12345678901",
    "address": "Rua 1",
    "city": "Cidade 1",
    "state": "Estado 1"
}

###

GET  http://localhost:3333/peoples
Content-Type: application/json

###

GET  http://localhost:3333/peoples/265d9c88-eb30-4289-881b-7606b8408083
Content-Type: application/json

###

PUT  http://localhost:3333/peoples/9874c065-613a-43d1-8017-9bc12345005e
Content-Type: application/json

{
    "name": "Dykson VictoR 2",
    "email": "dykson.tech@gmail.com",
    "birthDate": "1996-06-06",
    "phone": "12345678901",
    "address": "Rua 1",
    "city": "Cidade 1",
    "state": "Estado 1"
}

###

DELETE   http://localhost:3333/peoples/a8f91ea9-e650-4cc3-a9a9-f3f29f8632f4