POST http://localhost:3333/peoples
Content-Type: application/json

{
    "name": "Dykson Victor",
    "email": "dykson.marques3@gmail.com",
    "birthDate": "1996-06-06",
    "cpf": "47930854833",
    "phone": "12345678901",
    "address": "Rua 1",
    "city": "Cidade 1",
    "state": "Estado 1"
}

###

GET  http://localhost:3333/peoples
Content-Type: application/json

###

GET  http://localhost:3333/peoples/946b8133-e8c9-4f60-8a38-cd2405139813
Content-Type: application/json

###

PUT  http://localhost:3333/peoples/946b8133-e8c9-4f60-8a38-cd2405139810
Content-Type: application/json

{
    "name": "Dykson VictoR 2",
    "email": "dykson.tech@gmail.com",
    "birthDate": "1996-06-06",
    "phone": "12345678901",
    "address": "Rua 1",
    "city": "Cidade 1",
    "state": "Estado 1"
}

###

DELETE   http://localhost:3333/peoples/946b8133-e8c9-4f60-8a38-cd2405139810